### ISSUE TITLE
Planned features

### ISSUE THREAD

**Issue by Nyholm** [php-cache/cache-bundle#29]
This is a list of planned features: 

* [x] Logging - Log all cache transactions. 
* [x] Validation - It uses a cache from `Symfony\Component\Validator\Mapping\Cache\CacheInterface`
* [ ] Http - Instead of using disk, one maybe would like to use Redis for HttpCache
* [x] Serializer - It uses a doctrine cache
* [x] Annotation - It uses a doctrine cache
* [ ] Templating - This is just a string path to where templates should be stored
* [ ] Twig_CacheInterface

For each of these, investigate if it is a good idea to use a cache service.

**Comment by Nyholm** [comment]
I do not believe we can do anything about the templating since it just is a string. How about Http? I feels that it could be a separate package since it cant access anything in the bundle. 

So my question: Are we feature complete?

**Comment by aequasi** [comment]
Templates could be cached across servers, may still be worth doing? idk.

Http should be its own package

**Comment by Nyholm** [comment]
Sure, but how do you integrate that with symfony. As far as I know there is not point to inject that nicely like we did with the others.

**Comment by Nyholm** [comment]
I added `Twig_CacheInterface` to the list. Reference: https://www.reddit.com/r/PHP/comments/413hpc/as_an_experiment_i_wrote_two_alternative/
