### ISSUE TITLE
Move SessionHandler to a separate package

### ISSUE THREAD

**Issue by Nyholm** [php-cache/cache-bundle#40]
The Session handler is reusable. I think it should be moved to a separate package. I do also want to revisit my decision of  calling it the SessionHandlerBridge.

**Comment by aequasi** [comment]
Not really sure its worth moving to its own package. It's so common, and so easy to do, people don't really reuse them, they just make their own

**Comment by Nyholm** [comment]
> It's so common

Isn't that a reason to move it to a package?

It is not any drawback of putting it in a separate package. It will comply with the common reuse principle. We should however require this package by default.
