### ISSUE TITLE
Composer requires cache/taggable-cache ^0.1  dependency problem

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/cache-bundle#44]
When running

composer require cache/cache-bundle cache/doctrine-adapter-bundle

i get the following problem

Problem 1
    - Installation request for cache/cache-bundle ^0.2.0 -> satisfiable by cache/cache-bundle[0.2.0].
    - cache/cache-bundle 0.2.0 requires cache/taggable-cache ^0.1 -> no matching package found.
  Problem 2
    - cache/doctrine-adapter 0.2.0 requires cache/taggable-cache ^0.2 -> no matching package found.
    - cache/doctrine-adapter-bundle 0.2.0 requires cache/doctrine-adapter ^0.2 -> satisfiable by cache/doctrine-adapter[0.2.0].
    - Installation request for cache/doctrine-adapter-bundle ^0.2.0 -> satisfiable by cache/doctrine-adapter-bundle[0.2.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

I have already tried added this to composer.yml

"cache/taggable-cache": "0.3.1"

**Comment by PaddyLock** [comment]
I have also tried adding the following to composer, but no joy

"cache/taggable-cache": "^0.2.0@dev"

**Comment by Nyholm** [comment]
Can you post the relevant content of your composer.json? Im interested in the packages starting with `cache/`

**Comment by PaddyLock** [comment]
"cache/cache-bundle": "^0.2.0",
"cache/doctrine-adapter-bundle": "^0.2.0",

I also tried by adding

"cache/taggable-cache": "^0.2.0@dev"

**Comment by PaddyLock** [comment]
I also have

"minimum-stability": "stable",

**Comment by Nyholm** [comment]
Do `cache-bundle: dev-master` and change `doctrine-adapter-bundle` to `cache/adapter-bundle:^0.1`. The doctrine adapter bundle is soon to be deprecated.

**Comment by PaddyLock** [comment]
Thanks, what will replace doctrine-adapter-bundle once it is deprecated?

I have tried that. Now I get this:

  Problem 1
    - cache/doctrine-adapter 0.1.0 requires psr/cache 1.0.x-dev -> no matching package found.
    - Conclusion: don't install cache/doctrine-adapter-bundle 0.1.2
    - Conclusion: don't install cache/doctrine-adapter-bundle 0.1.1
    - cache/doctrine-adapter-bundle 0.1.0 requires cache/doctrine-adapter ^0.1 -> satisfiable by cache/doctrine-adapter[0.1.0, 0.1.1, 0.1.2].
    - Conclusion: don't install cache/doctrine-adapter 0.1.2
    - Conclusion: don't install cache/doctrine-adapter 0.1.1|don't install cache/taggable-cache 0.3.1|install cache/taggable-cache 0.1.2
    - Conclusion: don't install cache/taggable-cache 0.1.2
    - Installation request for cache/doctrine-adapter-bundle ^0.1 -> satisfiable by cache/doctrine-adapter-bundle[0.1.0, 0.1.1, 0.1.2].
    - Installation request for cache/cache-bundle dev-master -> satisfiable by cache/cache-bundle[dev-master].
    - Conclusion: remove cache/taggable-cache 0.3.1
    - cache/cache-bundle dev-master requires cache/taggable-cache ^0.2|^0.3 -> satisfiable by cache/taggable-cache[0.3.1, 0.2.0, 0.3.0].
    - Can only install one of: cache/taggable-cache[0.2.0, 0.1.0].
    - Can only install one of: cache/taggable-cache[0.3.0, 0.1.0].
    - cache/doctrine-adapter 0.1.1 requires cache/taggable-cache ^0.1 -> satisfiable by cache/taggable-cache[0.1.0, 0.1.1, 0.1.2].
    - Conclusion: don't install cache/taggable-cache 0.1.1|keep cache/taggable-cache 0.3.1|install cache/taggable-cache 0.3.1

**Comment by Nyholm** [comment]
> Thanks, what will replace doctrine-adapter-bundle once it is deprecated?

The `cache/adapter-bundle` is the replacement. As far as I know everything works in `cache/adapter-bundle`. I shipped it to production this morning at work. 

You should use the latest version (0.4.0) of `cache/doctrine-adapter`. That would solve your problem.

**Comment by PaddyLock** [comment]
sorry, my bad. I didn't change doctrine-adapter-bundle to doctrine-adapter. It now works with the following:

"cache/cache-bundle": "dev-master",
"cache/adapter-bundle": "^0.1"

However, this does mean that your readme is out of date.

Thanks for your help!

**Comment by Nyholm** [comment]
The readme of cache/cache-bundle is a bit old and should be moved to www.php-cache.com. 

Me and @aequasi will look over this shortly. We do also need to fix https://github.com/php-cache/cache-bundle/issues/39 before tagging cache-bundle with a new version. If you want to help it would be much appreciated.

**Comment by PaddyLock** [comment]
btw I tried with

"cache/adapter-bundle": "0.4.0"

and I got this

The requested package cache/adapter-bundle could not be found in any version, there may be a typo in the package name.

**Comment by Nyholm** [comment]
```json
// composer.json
 "cache/doctrine-adapter": "0.4",
 "cache/psr-6-doctrine-bridge": "^2.0.1", // <-- if you need it
 "cache/cache-bundle": "dev-master",
 "cache/adapter-bundle": "^0.1"
```

**Comment by PaddyLock** [comment]
Because I am using memcached I also seem to need

"cache/memcached-adapter": "^0.2.0"

However, I get an error 

[Cache\AdapterBundle\Exception\ConfigurationException]                                                                                                                                                                              
  Error while configure adapter helios_memcached. Verify your configuration at "cache_adapter.providers.helios_memcached.options". The options "hosts", "namespace", "persistent" do not exist. Defined options are: "host", "port".

in my configuration

cache_adapter:
  providers:
    default_memcached:
      factory: cache.factory.memcached
      options:
        persistent: true # Boolean or persistent_id
        namespace: mc
        hosts:
          - { host: localhost, port: 11211 }

cache:
  session:
    enabled: true
    service_id: cache.provider.acme_redis_cache
    ttl: 7200
  router:
    enabled: true
    service_id: cache.provider.acme_redis_cache
    ttl: 86400

I followed the docs here

http://www.php-cache.com/en/latest/symfony/cache-bundle/

**Comment by Nyholm** [comment]
The docs not updated here. Sorry for that. The proper options should be: 

```yaml
cache_adapter:
  providers:
    default_memcached:
      factory: cache.factory.memcached
      options:
        host: localhost 
        port: 11211
```

**Comment by PaddyLock** [comment]
Brilliant! 

final working composer:

"cache/doctrine-adapter": "0.4",
"cache/psr-6-doctrine-bridge": "^2.0.1",
"cache/cache-bundle": "dev-master",
"cache/adapter-bundle": "^0.1",
"cache/memcached-adapter": "^0.2.0"

final working config:

cache_adapter:
    providers:
        default_memcached:
            factory: cache.factory.memcached
            options:
                host: localhost
                port: 11211

cache:
    session:
        enabled: true
        service_id: cache.provider.default_memcached
        ttl: 7200
    router:
        enabled: true
        service_id: cache.provider.default_memcached
        ttl: 86400

**Comment by Nyholm** [comment]
Cool.
 Thank you for trying this out. Please open issues and send PRs if you find anything you like to improve.
